language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - frandzdypro@gmail.com