<?php

namespace OC\PlatformBundle\Entity;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{
	function getAllAdvertSkill($id){
		
		$qb = $this -> createQueryBuilder('ask')
			-> leftjoin('ask.advert','adv')
			-> addSelect("adv")
			-> leftjoin('ask.skill','sk')
			-> addSelect("sk") 
			-> where('adv.id = :id') 
			-> setParameter('id',$id);
		return $qb -> getQuery() -> getResult();
	}
}
