<?php

namespace OC\PlatformBundle\Entity;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function getAdvertWithCategories($id)
    {
        $qb = $this->createQueryBuilder('a')
            ->where("a.id = :id");
        $qb->setParameter("id", $id);

        return $qb->getQuery()->getSingleResult();
    }

    /**
     * @param $search
     * @return array
     */
    public function getSearch($search)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where($qb->expr()->like("a.title", ':s'));
        $qb->setParameter("s", "%" . $search . "%");
        return $qb->getQuery()->getResult();
    }

    /**
     * @param $id
     * @return mixed
     */
    public function  findPostUser($id)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->where("a.author = :id");
        $qb->setParameter("id", $id);

        return $qb->getQuery()->getResult();
    }

}

