<?php

namespace OC\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getApplicationsWithAdvert($id){
		/**
		 * Requête left join plus parameter et limit 
		 */
		$qb = $this -> createQueryBuilder('a')
			-> leftjoin('a.advert','adv')
			-> where('adv.id = :id')
			-> setParameter('id',$id);
		return $qb -> getQuery() -> getResult();
	}
}
