<?php

namespace OC\PlatformBundle\Entity;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCiviliteRepository extends \Doctrine\ORM\EntityRepository
{

}

