<?php

namespace OC\PlatformBundle\Entity;

/**
 * RefSexeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefSexeRepository extends \Doctrine\ORM\EntityRepository
{

}

